from BaseClasses import ItemClassification
from typing import TypedDict, List

from BaseClasses import Item


base_id = 147000


class InscryptionItem(Item):
    name: str = "Inscryption Beta"


class ItemDict(TypedDict):
    name: str
    count: int
    classification: ItemClassification


act1_items: List[ItemDict] = [
    {'name': "Stinkbug Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Stunted Wolf Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Wardrobe Key",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Skink Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Ant Cards",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Caged Wolf Card",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Squirrel Totem Head",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Dagger",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Film Roll",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Ring",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Magnificus Eye",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Oil Painting's Clover Plant",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Extra Candle",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Bee Figurine",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Greater Smoke",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Angler Hook",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Woodcarver Node",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Trader Node",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Mycologists Node",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Bone Altar Node",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Sacrifice Stones Node",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Backpack Node",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Campfire Node",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Goobert Node",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Smaller Backpack Challenge",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Expensive Pelts Challenge",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Totem Bosses Challenge",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Progressive Tipped Scales",
     'count': 4,
     'classification': ItemClassification.progression},
    {'name': "All Totem Battles Challenge",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "More Difficult Challenge",
     'count': 2,
     'classification': ItemClassification.progression},
    {'name': "Progressive Candle",
     'count': 2,
     'classification': ItemClassification.progression},
    {'name': "Progressive Squirrel",
     'count': 2,
     'classification': ItemClassification.progression},
    {'name': "Progressive Grizzlies",
     'count': 3,
     'classification': ItemClassification.progression}
]


act2_items: List[ItemDict] = [
    {'name': "Camera Replica",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Pile Of Meat",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Epitaph Piece",
     'count': 9,
     'classification': ItemClassification.progression},
    {'name': "Epitaph Pieces",
     'count': 3,
     'classification': ItemClassification.progression},
    {'name': "Monocle",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Bone Lord Femur",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Bone Lord Horn",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Ancient Obol",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Great Kraken Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Drowned Soul Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Salmon Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Dock's Clover Plant",
     'count': 1,
     'classification': ItemClassification.useful}
]


act3_items: List[ItemDict] = [
    {'name': "Extra Battery",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Nano Armor Generator",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Mrs. Bomb's Remote",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Inspectometer Battery",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Gems Module",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Lonely Wizbot Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Fishbot Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Ourobot Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Holo Pelt",
     'count': 5,
     'classification': ItemClassification.progression},
    {'name': "Quill",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Bone Lord Holo Key",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Mycologists Holo Key",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Foul Backwater Shortcut",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Filthy Corpse World Shortcut",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Gaudy Gem Land Shortcut",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Vessel Upgrade",
     'count': 3,
     'classification': ItemClassification.useful},
    {'name': "Conduit Upgrade",
     'count': 1,
     'classification': ItemClassification.useful},
]

act2_3_items: List[ItemDict] = [
    {'name': "Hammer",
     'count': 1,
     'classification': ItemClassification.useful},
]

act_items: List[ItemDict] = [
    {'name': "Act 1",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Act 2",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Act 3",
     'count': 1,
     'classification': ItemClassification.progression},
]

filler_items: List[ItemDict] = [
    {'name': "Currency",
     'count': 1,
     'classification': ItemClassification.filler},
    {'name': "Card Pack",
     'count': 1,
     'classification': ItemClassification.filler}
]

trap_items: List[ItemDict] = [
    {'name': "Bleach Trap",
     'count': 1,
     'classification': ItemClassification.trap},
    {'name': "Trash Trap",
     'count': 1,
     'classification': ItemClassification.trap},
    {'name': "Deck Size Trap",
     'count': 1,
     'classification': ItemClassification.trap},
    {'name': "Reinforcements Trap",
     'count': 1,
     'classification': ItemClassification.trap}
]
